openapi: 3.0.1
info:
  title: Swagger Api Acme - Emissão de Apólices - OpenAPI 3.0
  description: |-
    Itau Challenge Project
  termsOfService: http://swagger.io/terms/
  contact:
    email: miguel.silva@mackenzista.com.br
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.12
tags:
  - name: apolice
    description: "Cria, atualiza uma apólice"

  - name: apolice-consulta
    description: "Consulta uma apólice"

paths:

  /v1/apolice/emite:
    post:
      tags:
        - apolice
      summary: cria uma apólice
      description: Cria uma apólice a partir de atributos
      operationId: geraApolice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Apolice"
      responses:
        '201':
          description: Apólice criada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApoliceResponse"
        '400':
          description: Não foi possível criar apólice

  /v1/apolice/consulta:
    get:
      tags:
        - apolice-consulta
      summary: Consulta uma apólice
      description: Retorna uma apólice
      operationId: consutaApolice
      parameters:
        - in: query
          name: clienteId
          schema:
            type: string
            format: uuid
        - in: query
          name: solicitacaoId
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Apólice encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApoliceResponse"
        '400':
          description: Não foi possível localizar apólice
        '404':
          description: Erro tentar localizar apólice


components:
  schemas:

    ApoliceConsulta:
      type: object
      properties:
        clienteId:
          type: string
          format: uuid
        produtoId:
          type: string
          format: uuid
        categoria:
          $ref: "#/components/schemas/CategoriaSeguro"
        metodoPagemento:
          $ref: "#/components/schemas/TipoPagamento"
        valorTotalPremioMensal:
          type: number
          format: double
        valorSegurado:
          type: number
          format: double
        cobertura:
            $ref: "#/components/schemas/Cobertura"
        assistencias:
          type: array
          items:
            $ref: "#/components/schemas/TipoAssistencia"

    Apolice:
      type: object
      properties:
        clienteId:
          type: string
          format: uuid
        produtoId:
          type: string
          format: uuid
        categoria:
          $ref: "#/components/schemas/CategoriaSeguro"
        origem:
          $ref: "#/components/schemas/TipoCanalVendas"
        metodoPagemento:
          $ref: "#/components/schemas/TipoPagamento"
        valorTotalPremioMensal:
          type: number
          format: double
        valorSegurado:
          type: number
          format: double
        cobertura:
          $ref: "#/components/schemas/Cobertura"
        assistencias:
          type: array
          items:
            $ref: "#/components/schemas/TipoAssistencia"

    ApoliceResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        clienteId:
          type: string
          format: uuid
        produtoId:
          type: string
          format: uuid
        categoria:
          $ref: "#/components/schemas/CategoriaSeguro"
        metodoPagemento:
          $ref: "#/components/schemas/TipoPagamento"
        status:
          $ref: "#/components/schemas/Estado"
        dataInicio:
          type: string
          format: date
        dataFinalizacao:
          type: string
          format: date
        valorTotalPremioMensal:
          type: number
          format: double
        valorSegurado:
          type: number
          format: double
        cobertura:
            $ref: "#/components/schemas/Cobertura"
        assistencias:
          type: array
          items:
            $ref: "#/components/schemas/TipoAssistencia"
        historico:
          type: array
          items:
            $ref: "#/components/schemas/Historico"

    Cobertura:
      type: object
      properties:
        roubo:
          type: number
          format: double
        perdaTotal:
          type: number
          format: double
        colisaoTerceiros:
          type: number
          format: double

    TipoAssistencia:
      type: string
      enum:
        - GUINCHO
        - TROCA_DE_OLEO
        - CHAVEIRO

    TipoCanalVendas:
      type: string
      enum:
        - MOBILE
        - WHATSAPP
        - WEB_SITE

    TipoPagamento:
      type: string
      enum:
        - CARTAO_CREDITO
        - DEBITO_EM_CONTA
        - BOLETO
        - PIX

    CategoriaSeguro:
      type: string
      enum:
        - VIDA
        - AUTO
        - RESIDENCIAL
        - EMPRESARIAL

    Estado:
      type: string
      enum:
        - RECEBIDO
        - VALIDADO
        - PENDENTE
        - REJEITADO
        - APROVADO
        - CANCELADA

    Historico:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Estado'
        data:
          type: string
          format: date