openapi: 3.0.1
info:
  title: ACME - API de Emissão e Consulta de Apólices
  description: |-
    # Itau Challenge Project  

    Esta API permite **emitir** e **consultar apólices de seguros**.  
    Foi desenvolvida seguindo o conceito **API-First**, garantindo que o contrato
    esteja definido antes da implementação.

    ---
    ## Desenvolvedores
    - Miguel Pereira da Silva (miguel.silva@mackenzista.com.br)
    - Equipe ACME - Squad de Seguros Digitais
  version: 1.0.12
  termsOfService: http://swagger.io/terms/
  contact:
    name: Equipe de Desenvolvimento ACME
    email: miguel.silva@mackenzista.com.br
    url: https://github.com/miguelsilva
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png
    backgroundColor: "#FFFFFF"
    altText: "Logo ACME"

tags:
  - name: apolice
    description: "Cria, atualiza uma apólice"
  - name: apolice-consulta
    description: "Consulta uma apólice"
  - name: apolice-consulta-cliente
    description: "Consulta uma apólice por cliente"

paths:
  /v1/apolice:
    post:
      tags:
        - apolice
      summary: Cria uma apólice
      description: Cria uma apólice a partir de atributos
      operationId: geraApolice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Apolice"
      responses:
        '201':
          description: Apólice criada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApoliceResponse"
        '400':
          description: Não foi possível criar apólice

  /v1/apolice/{id}:
    get:
      tags:
        - apolice-consulta
      summary: Consulta apólice por Id apólice ou Id client
      description: Retorna uma ou mais apólices
      operationId: listaApolice
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
            example: "Id apolice 3fa85f64-5717-4562-b3fc-2c963f66afa6"
      responses:
        '200':
          description: Apólices encontrada
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApoliceConsulta"
        '400':
          description: Erro tentar localizar apólice
        '404':
          description: Não foi possível localizar apólice

  /v1/clientes/{idCliente}/apolice:
    get:
      tags:
        - apolice-consulta-cliente
      summary: Lista de apólices por Id cliente
      description: Retorna uma ou mais apólices
      operationId: listaApolicePorCliente
      parameters:
        - in: path
          name: idCliente
          required: true
          schema:
            type: string
            format: uuid
            example: "Id apolice 3fa85f64-5717-4562-b3fc-2c963f66afa6"
      responses:
        '200':
          description: Apólices encontrada
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ApoliceConsulta"
        '400':
          description: Erro tentar localizar apólice
        '404':
          description: Não foi possível localizar apólice


components:
  schemas:

    ApoliceConsulta:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "9fa85f64-5717-4562-b3fc-2c963f66afa6"
        clienteId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        produtoId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        categoria:
          $ref: "#/components/schemas/CategoriaSeguro"
        metodoPagemento:
          $ref: "#/components/schemas/TipoPagamento"
        status:
          $ref: "#/components/schemas/Estado"
        dataInicio:
          type: string
          format: date-time
          example: "2025-08-25T10:30:00-03:00"
        dataFinalizacao:
          type: string
          format: date-time
          example: "2025-08-25T10:30:00-03:00"
        valorTotalPremioMensal:
          type: number
          format: double
          example: 200.00
        valorSegurado:
          type: number
          format: double
          example: 100000.00
        cobertura:
          $ref: "#/components/schemas/Cobertura"
        assistencias:
          type: array
          items:
            type: string
          example:
            - "Guincho até 250km"
            - "Troca de Óleo"
            - "Chaveiro 24h"
        historico:
          type: array
          items:
            $ref: "#/components/schemas/Historico"

    Apolice:
      type: object
      properties:
        clienteId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        produtoId:
          type: string
          format: uuid
          example: "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        categoria:
          $ref: "#/components/schemas/CategoriaSeguro"
        origem:
          $ref: "#/components/schemas/TipoCanalVendas"
        metodoPagemento:
          $ref: "#/components/schemas/TipoPagamento"
        valorTotalPremioMensal:
          type: number
          format: double
          example: 150.00
        valorSegurado:
          type: number
          format: double
          example: 100000.00
        cobertura:
          $ref: "#/components/schemas/Cobertura"
        assistencias:
          type: array
          items:
            type: string
          example:
            - "Guincho até 250km"
            - "Troca de Óleo"
            - "Chaveiro 24h"

    ApoliceResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "9fa85f64-5717-4562-b3fc-2c963f66afa6"
        dataInicio:
          type: string
          format: date-time
          example: "2025-08-25T10:30:00-03:00"

    Cobertura:
      type: object
      properties:
        roubo:
          type: number
          format: double
          example: 100000.25
        perdaTotal:
          type: number
          format: double
          example: 100000.25
        colisaoTerceiros:
          type: number
          format: double
          example: 75000.00

    TipoCanalVendas:
      type: string
      enum:
        - MOBILE
        - WHATSAPP
        - WEB_SITE
      example: MOBILE

    TipoPagamento:
      type: string
      enum:
        - CARTAO_CREDITO
        - DEBITO_EM_CONTA
        - BOLETO
        - PIX
      example: CARTAO_CREDITO

    CategoriaSeguro:
      type: string
      enum:
        - VIDA
        - AUTO
        - RESIDENCIAL
        - EMPRESARIAL
      example: AUTO

    Estado:
      type: string
      enum:
        - RECEBIDO
        - VALIDADO
        - PENDENTE
        - REJEITADO
        - APROVADO
        - CANCELADA
      example: RECEBIDO

    Historico:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Estado'
        data:
          type: string
          format: date-time
          example: "2025-08-25T10:30:00-03:00"
